pr:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
    updateAssemblyInfo: true
- bash: |
    echo '##vso[build.updatebuildnumber]$(GitVersion.NuGetVersion)'
  displayName: "Set build version"
- bash: |
    echo '##vso[task.setvariable variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE]true'
    echo '##vso[task.setvariable variable=DOTNET_CLI_TELEMETRY_OPTOUT]true'
  displayName: "Disable some .NET Core telemetry and cache setup"
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: sdk
    version: 2.1.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: 'Nuget Retore'
  inputs:
    command: 'restore'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    arguments: '--no-restore --configuration Release'
- task: DotNetCoreCLI@2
  displayName: 'Pack'
  inputs:
    command: 'pack'
    arguments: '-p:PackageVersion=$(GitVersion.NuGetVersion) --no-restore --include-symbols --configuration Release'
