pr:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  displayName: "Disable some .NET Core telemetry and cache setup"
  - bash: |
    echo '##vso[task.setvariable variable=DOTNET_SKIP_FIRST_TIME_EXPERIENCE]true'
    echo '##vso[task.setvariable variable=DOTNET_CLI_TELEMETRY_OPTOUT]true'
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: sdk
    version: 3.1.100
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: 'Nuget Retore'
  inputs:
    command: 'restore'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    arguments: '--no-restore'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    arguments: '--no-restore'
