steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK'
  inputs:
    packageType: sdk
    version: 3.1.100
    installationPath: $(Agent.ToolsDirectory)/dotnet
- task: DotNetCoreCLI@2
  displayName: 'Install tools'
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'
- task: DotNetCoreCLI@2
  displayName: 'Install tools'
  inputs:
    command: 'custom'
    custom: 'cake'
    arguments: '--target=Build'